Repository hellozo0/Gulp, pull requests merged in 2025-04, with the labels that each got.

#7 feat : db.json 더미 데이터 추가
  gulp-web/db.json
  gulp-web/package-lock.json
  node_modules/.vue-global-types/vue_3.5_0_0_0.d.ts
  node_modules/.vue-global-types/vue_99_0_0_0.d.ts
Labels: 현주

#8 반응형은 진행중 - 맨마지막에 수정예정
  gulp-web/index.html
  gulp-web/package-lock.json
  gulp-web/package.json
  gulp-web/src/App.vue
  gulp-web/src/main.js
  gulp-web/src/pages/Home.vue
Labels: 채은

#20 feat : 사진과 pinia 추가
  gulp-web/package-lock.json
  gulp-web/package.json
  gulp-web/src/assets/images/AngryMoney.png
  gulp-web/src/assets/images/HappyHoney.png
  gulp-web/src/assets/images/HappyMoney.png
  gulp-web/src/assets/images/PointingHoney.png
  gulp-web/src/assets/images/SadHoney.png
  gulp-web/src/assets/images/SmileMoeny.png
  gulp-web/src/assets/images/duty.png
  gulp-web/src/assets/images/excited.png
  gulp-web/src/assets/images/happy.png
  gulp-web/src/assets/images/logo_2d.png
  gulp-web/src/assets/images/regret.png
  gulp-web/src/assets/images/stress.png
  gulp-web/src/main.js
  gulp-web/src/stores/budgetStore.js
Labels: 정우

#23 feat : 최신순 조회 수정, 월별 순수익 계산 컴포넌트
  gulp-web/src/components/NetProfit.vue
  gulp-web/src/components/SortByLatest.vue
  gulp-web/src/pages/Home.vue
Labels: 채은

#25 feat : 지출 상위 4개 항목
  gulp-web/package-lock.json
  gulp-web/package.json
  gulp-web/src/assets/icons/beauty.png
  gulp-web/src/assets/icons/education.png
  gulp-web/src/assets/icons/entertainment.png
  gulp-web/src/assets/icons/etc.png
  gulp-web/src/assets/icons/food.png
  gulp-web/src/assets/icons/hobby.png
  gulp-web/src/assets/icons/housing.png
  gulp-web/src/assets/icons/icon 15.png
  gulp-web/src/assets/icons/insurance.png
  gulp-web/src/assets/icons/life.png
  gulp-web/src/assets/icons/loan.png
  gulp-web/src/assets/icons/medical.png
  gulp-web/src/assets/icons/saving.png
  gulp-web/src/assets/icons/shopping.png
  gulp-web/src/assets/icons/transfer.png
  gulp-web/src/assets/icons/transport.png
  gulp-web/src/components/BySpending.vue
  gulp-web/src/components/Footer.vue
  gulp-web/src/components/NetProfit.vue
  gulp-web/src/components/SortByLatest.vue
  gulp-web/src/pages/Home.vue
Labels: 채은

#35 feat: Filter 추가 완료 달력과 연동 예정
  gulp-web/package-lock.json
  gulp-web/package.json
  gulp-web/src/pages/History.vue
  gulp-web/src/stores/budgetStore.js
Labels: 정우

#38 [feat] 필터 기능 추가
  gulp-web/package-lock.json
  gulp-web/package.json
  gulp-web/src/main.js
  gulp-web/src/pages/History.vue
Labels: 정우

#42 FEAT#34 : 내역 상세보기, 수정 모달 창 추가
  gulp-web/db.json
  gulp-web/src/components/EditModal.vue
  gulp-web/src/components/TransactionModal.vue
  gulp-web/src/pages/History.vue
Labels: 다연

#46 FEAT#44 pinia적용 + 디자인 수정 완료
  gulp-web/db.json
  gulp-web/src/components/EditModal.vue
  gulp-web/src/components/QuickCreate.vue
  gulp-web/src/components/TransactionModal.vue
  gulp-web/src/pages/History.vue
  gulp-web/src/stores/budgetStore.js
Labels: 다연
